### PR TITLE
Increase timeout for policy server requests

### LINKED ISSUE #108: Figure out where the 2 second context timeout is coming from
Long-running requests typically fail due to "context cancelled" after about 2 seconds, but it's not clear where that cancellation is coming from.

While we're here, we should evaluate our context usage and make it more proper too. We're almost certainly doing something wrong with how contexts are shared, which might be contributing to the early timeout.

Impact of this is it can sometimes take multiple `/sign` requests before an event is approved/declined, especially when using the HMA filter or another filter that takes a long time.

### PR DESCRIPTION
**Pull request by turt2live**
This is to accommodate media scanning and checking. Currently, a 3s timeout means we make 2-5 requests before a media item is successfully scanned. 

Number chosen based on vibes and light real world testing.

Fixes https://github.com/matrix-org/policyserv/issues/108

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Review by anoadragon453 — APPROVED** [review]

File: changelog.d/19629.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+Increase timeout for policy server requests to avoid repeated requests for checking media.
```
Comment (MadLittleMods) [inline changelog.d/19629.bugfix:1]: > [...] Currently, a 3s timeout means we make 2-5 requests before a media item is successfully scanned.

I'm not following what this means?

File: synapse/handlers/room_policy.py [hunk 2]
```diff
@@ -228,7 +228,7 @@ async def ask_policy_server_to_sign_event(
             signature = await self._federation_client.ask_policy_server_to_sign_event(
                 policy_server.server_name,
                 event,
-                timeout=3000,
+                timeout=30000,
```
Comment (MadLittleMods) [inline synapse/handlers/room_policy.py:231]: Comment our current reasoning why we chose this value

And what we need to look out for (scanning media which can take a while)

File: changelog.d/19629.bugfix (hunk 1 above)
Comment (MadLittleMods) [reply changelog.d/19629.bugfix:1]: Perhaps: Because we often hit the timeout, we have to make 2-5 requests before it goes through successfully

File: synapse/handlers/room_policy.py (hunk 2 above)
Comment (turt2live) [reply synapse/handlers/room_policy.py:231]: there's a comment above the function call

File: changelog.d/19629.bugfix (hunk 1 above)
Comment (turt2live) [reply changelog.d/19629.bugfix:1]: your assumption is correct

File: synapse/handlers/room_policy.py (hunk 2 above)
Comment (MadLittleMods) [reply synapse/handlers/room_policy.py:231]: Current: https://github.com/element-hq/synapse/blob/f772fad1cd7ab86e76fe86481792214e33270e78/synapse/handlers/room_policy.py#L225-L232

Given this PR, there are new things to think about here

**Comment by anoadragon453** [comment]
Failing Complement job is just due to a [flaky](https://github.com/element-hq/synapse/issues/18537) test (`TestThreadReceiptsInSyncMSC4102`).

File: synapse/handlers/room_policy.py (hunk 2 above)
Comment (MadLittleMods) [reply synapse/handlers/room_policy.py:231]: This PR was merged without any change.

I've documented the reasoning in https://github.com/element-hq/synapse/pull/19633

Comment (turt2live) [reply synapse/handlers/room_policy.py:231]: I didn't realize this was a blocking concern - it wasn't a requested change, sorry. I still feel the existing comment is appropriate - we have git history to tell us any additional stories if needed.

Comment (MadLittleMods) [reply synapse/handlers/room_policy.py:231]: Git history is a last resort for trying to find the root cause and unfortunately, most of the time, people don't document their reasoning even in their PR's. Luckily, we at-least have that here :thumbsup:

But we also want to make our decisions clear from the code itself, not to make it reconstructible with enough archaeology. Doing this is nice because it's easy to make a decision again in the future.
