### PR TITLE
Fix support for older versions of zope-interface

### LINKED ISSUE #19269: Server crash, cannot start. TypeError: unsupported operand type(s) for |: 'InterfaceClass' and 'NoneType'
### Description

 #19111 broke my synapse pretty badly. I get the following error throughout a lot of places. I cannot run it any more.
```
TypeError: unsupported operand type(s) for |: 'InterfaceClass' and 'NoneType'
```
running wuth python3.11, installed with pip
 

### Steps to reproduce

- update to version 1.143.0
- synctl start

### Homeserver

neo.matteodroids.science

### Synapse Version

Requirement already satisfied: matrix-synapse[postgres] in ./.local/lib/python3.11/site-packages (1.143.0)

### Installation Method

pip (from PyPI)

### Database

PostgreSQL

### Workers

Single process

### Platform

Opensuse Leap 15.6

### Configuration

_No response_

### Relevant log output

```shell
+ synctl start
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/matrix-synapse/.local/lib/python3.11/site-packages/synapse/app/homeserver.py", line 32, in <module>
    from synapse import events
  File "/opt/matrix-synapse/.local/lib/python3.11/site-packages/synapse/events/__init__.py", line 46, in <module>
    from synapse.util.caches import intern_dict
  File "/opt/matrix-synapse/.local/lib/python3.11/site-packages/synapse/util/caches/__init__.py", line 35, in <module>
    from synapse.util.metrics import DynamicCollectorRegistry
  File "/opt/matrix-synapse/.local/lib/python3.11/site-packages/synapse/util/metrics.py", line 36, in <module>
    from synapse.logging.context import (
  File "/opt/matrix-synapse/.local/lib/python3.11/site-packages/synapse/logging/__init__.py", line 24, in <module>
    from synapse.logging._remote import RemoteHandler
  File "/opt/matrix-synapse/.local/lib/python3.11/site-packages/synapse/logging/_remote.py", line 100, in <module>
    class RemoteHandler(logging.Handler):
  File "/opt/matrix-synapse/.local/lib/python3.11/site-packages/synapse/logging/_remote.py", line 116, in RemoteHandler
    _reactor: IReactorTime | None = None,
              ~~~~~~~~~~~~~^~~~~~
TypeError: unsupported operand type(s) for |: 'InterfaceClass' and 'NoneType'
synapse.app.homeserver(homeserver.yaml) failed to start (exit code: 1). Check the Synapse logfile, or run synctl with --no-daemonize.
```

### Anything else that would be useful to know?

_No response_

### PR DESCRIPTION
**Pull request by devonh**
Fixes #19269 

Versions of zope-interface from RHEL, Ubuntu LTS 22 & 24 and OpenSuse don't support the new python union `X | Y` syntax for interfaces. This PR partially reverts the change over to fully use the new syntax, adds a minimum supported version of zope-interface to Synapse's dependency list, and removes the linter auto-upgrades which prefer the newer syntax.

### Pull Request Checklist

* [X] Pull request is based on the develop branch
* [X] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [X] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

File: changelog.d/19274.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix bug introduced in 1.143.0 that broke support for older versions of zope-interface.
```
Comment (MadLittleMods) [inline changelog.d/19274.bugfix]: Aside: This was not "ready for review" when marked as such.

Might as well submit the PR as draft until everything is settled.

(changelog added, CI passing, etc)

File: pyproject.toml [hunk 2]
```diff
@@ -40,6 +40,14 @@ dependencies = [
...
     # RHEL 9: 22.10)
     "Twisted[tls]>=21.2.0",
+    # We don't explicitly depend on zope-interface. Twisted pulls it in implicitly as a dependency.
+    # We add an explicit dependency here to ensure the versions of zope-interface Synapse supports
+    # includes those which are available on our supported platforms.
+    # Specifying the dependency explicitly will ensure we test with the lowest version during the
+    # olddeps CI tests.
+    # 5.2 is the current version in Debian oldstable. If we don't care to support that, then 5.4 is
+    # the minimum version from Ubuntu 22.04 and RHEL 9. (as of 2025-12)
+    "zope-interface>=5.2",
```
Comment (anoadragon453) [inline pyproject.toml]: We may need to move/update this now that https://github.com/element-hq/synapse/pull/19289 has merged?

File: changelog.d/19274.bugfix (hunk 1 above)
Comment (anoadragon453) [inline changelog.d/19274.bugfix]:
```suggestion
Fix bug introduced in 1.143.0 that broke support for versions of `zope-interface` older than 6.2.
```

File: pyproject.toml [hunk 3]
```diff
@@ -40,6 +40,14 @@ dependencies = [
     # lives hard (as of 2025-07, distro support is Ubuntu LTS: 22.1, Debian stable: 22.4,
     # RHEL 9: 22.10)
     "Twisted[tls]>=21.2.0",
+    # We don't explicitly depend on zope-interface. Twisted pulls it in implicitly as a dependency.
+    # We add an explicit dependency here to ensure the versions of zope-interface Synapse supports
+    # includes those which are available on our supported platforms.
+    # Specifying the dependency explicitly will ensure we test with the lowest version during the
+    # olddeps CI tests.
```
Comment (anoadragon453) [inline pyproject.toml]: Not the case anymore!

File: pyproject.toml [hunk 4]
```diff
@@ -40,6 +40,14 @@ dependencies = [
...
+    # 5.2 is the current version in Debian oldstable. If we don't care to support that, then 5.4 is
+    # the minimum version from Ubuntu 22.04 and RHEL 9. (as of 2025-12)
+    "zope-interface>=5.2",
     "treq>=21.5.0",
```
Comment (anoadragon453) [inline pyproject.toml:43]: Can you reference this PR in this comment, so we know we can re-do the `|` syntax once we bump the minimum past 6.2?

File: pyproject.toml (hunk 2 above)
Comment (devonh) [reply pyproject.toml]: Indeed, I will do that now :)
