### PR TITLE
Send a SSS response immediately if the config has changed and there are new results to sync

### LINKED ISSUE #18844: Sliding Sync: Rooms with new requested `required_state` aren't sent until other activity occurs
### Description

Changing the `required_state` but preserving the current `pos` offset will result in no new data being passed down. 
This seems to be a bug as the spec states that ["if new entries are added to `required_state` then the server must send down matching current state events"](https://github.com/matrix-org/matrix-spec-proposals/pull/4186).

Originally reported [here](https://matrix.to/#/!cnVVNLKqgUzNTOFQkz:matrix.org/$y6SS3N6s8jXkvMRa6q4qbQrJy4M0qIGXmD5UDsvlCRM?via=element.io&via=matrix.org&via=one.ems.host), can provide network logs on request.

### Steps to reproduce

- Have a client that preserves the sliding sync `pos` e.g. Element X iOS
- Update said client so it requests more state the next time it run e.g. `["m.space.parent", "*"]`, `["m.space.child", "*"]`
- Observe how no new state gets passed down in subsequent requests.

### Homeserver

matrix.org

### Synapse Version

1.136.0 (b=matrix-org-hotfixes-priv,a4db588e87)

### Installation Method

I don't know

### Database

-

### Workers

Single process

### Platform

-

### Configuration

_No response_

### Relevant log output

```shell
-
```

### Anything else that would be useful to know?

_No response_

### LINKED ISSUE #19713: Sliding Sync: a room subscription doesn't imply an immediate sync response
## Steps to reproduce (STR)

- with Simplified Sliding Sync (SSS), subscribe to a room, with a specific `timeline_limit` (20) that's different from the room list `timeline_limit` parameter (1)

### Expected

If there were more than 1 message in the room, the server should immediately return a sync response, with the room portion of that response including more events in the timeline portion.

### Observed

The server doesn't return a new sync response at all. I suspect this is an optimization, and that the next activity in the room would trigger a sync response taking into account updated parameters, but this optimization wouldn't be technically correct.

This causes failures like https://github.com/element-hq/element-x-ios/issues/5189, where the EXI app will subscribe to rooms visible on screen, and inactive rooms never get a proper latest message in the room list.

## Integration test

For convenience, there's an integration test in the Matrix Rust SDK on this branch: https://github.com/matrix-org/matrix-rust-sdk/tree/bnjbvr/integration-test-timeline-limit-subscribe-buggy

To run it:

- tweak the source of the docker image in `testing/matrix-sdk-integration-testing/assets/Dockerfile`
- set up instances: `cd testing/matrix-sdk-integration-testing && podman-compose -f ./assets/docker-compose.yml up`
- run the test (from SDK repo root): `cargo nextest run --manifest-path ./testing/matrix-sdk-integration-testing/Cargo.toml --retries 0 -- test_latest_event_few_rooms`

### Homeserver

local synapse instance

### Synapse Version

v1.151.0 from docker hub

### Installation Method

Docker (matrixdotorg/synapse)

### Database

not sure

### Workers

I don't know

### Platform

archlinux btw

### PR DESCRIPTION
**Pull request by bnjbvr**
This fixes the bug described in #19713 (and double-checked against the SDK integration test, which now passes with this change). A sync response must be returned immediately if a room subscription configuration change caused a new non-empty response (checked with `if response` in the code) to be produced.

Fixes #19713.
Fixes #18844.

### CODE REVIEW

**Review by erikjohnston — APPROVED** [review]
Thanks for finding this!

File: changelog.d/19714.bugfix [hunk 1]
```diff
@@ -0,0 +1 @@
+Have SSS return a new response immediately if a room subscription have changed and produced a new response.
```
Comment (MadLittleMods) [inline changelog.d/19714.bugfix:1]: The PR description says this fixes https://github.com/element-hq/synapse/issues/18844

But I don't see an associated test update as described in https://github.com/element-hq/synapse/issues/18844#issuecomment-3201038729

File: synapse/handlers/sliding_sync/__init__.py [hunk 2]
```diff
@@ -167,34 +167,38 @@ async def wait_for_sync_for_user(
...
-                timeout_ms,
-                current_sync_callback,
-                from_token=from_token.stream_token,
-            )
-            did_wait = True
+        result = await self.notifier.wait_for_events(
+            sync_config.user.to_string(),
+            timeout_ms,
+            current_sync_callback,
+            from_token=now_token,
```
Comment (MadLittleMods) [inline synapse/handlers/sliding_sync/__init__.py:199]: Just to make sure I'm following this logic, we use `now_token` here because we already checked for data between `from_token` -> `now_token` with the first `current_sync_for_user(...)` call above and found nothing. So we can save trying to lookup anything in that range and jump from `now_token` -> token after waiting

Feels like this deserves a comment as an optimization. Something along the lines of `from_token.stream_token` still being the right answer but we can save ... because ...

File: changelog.d/19714.bugfix (hunk 1 above)
Comment (MadLittleMods) [reply changelog.d/19714.bugfix:1]: Looks like https://github.com/element-hq/synapse/pull/19734 is trying to address this

File: synapse/handlers/sliding_sync/__init__.py (hunk 2 above)
Comment (MadLittleMods) [reply synapse/handlers/sliding_sync/__init__.py:199]: Looks like https://github.com/element-hq/synapse/pull/19734 is trying to address this
